# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'LIED_LOLv2_synthetic'

# Optimization arguments.
OPTIM:
  BATCH: 8
  EPOCHS: 3000
  # EPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: '/data/lowlight_data/LOLv2/Synthetic/Train'       # path to training data
  VAL_DIR: '/data/lowlight_data/LOLv2/Synthetic/Test' # path to validation data
  SAVE_DIR: './checkpoints'